// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5w7p28hdUUNcfv37nniItpuHE0aJbLPk',
    appId: '1:329158450498:web:a181e3b4587c12b1403cdb',
    messagingSenderId: '329158450498',
    projectId: 'lakbay-cd97e',
    authDomain: 'lakbay-cd97e.firebaseapp.com',
    storageBucket: 'lakbay-cd97e.appspot.com',
    measurementId: 'G-H1JW2F2DPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_23hwBioqNkEcDlDV1fA9mmJpHNnXy7Y',
    appId: '1:329158450498:android:e6364cfa8c0e5819403cdb',
    messagingSenderId: '329158450498',
    projectId: 'lakbay-cd97e',
    storageBucket: 'lakbay-cd97e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcrwSvJq6zkKgKHSlTTq76EMCgqJbQlDA',
    appId: '1:329158450498:ios:9930bb0c0395d2b8403cdb',
    messagingSenderId: '329158450498',
    projectId: 'lakbay-cd97e',
    storageBucket: 'lakbay-cd97e.appspot.com',
    iosBundleId: 'com.example.lakbay',
  );
}
